# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.api.chats_api import ChatsApi


class TestChatsApi(unittest.TestCase):
    """ChatsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChatsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_message(self) -> None:
        """Test case for delete_message

        Delete a message
        """
        pass

    def test_list_activity_messages(self) -> None:
        """Test case for list_activity_messages

        List all messages (comments) for the activity
        """
        pass

    def test_list_chats(self) -> None:
        """Test case for list_chats

        List chats for the athlete, most recently active first
        """
        pass

    def test_list_messages(self) -> None:
        """Test case for list_messages

        List messages for the chat, most recent first
        """
        pass

    def test_send_activity_message(self) -> None:
        """Test case for send_activity_message

        Add a message (comment) to an activity
        """
        pass

    def test_send_message(self) -> None:
        """Test case for send_message

        Send a message
        """
        pass

    def test_show_chat(self) -> None:
        """Test case for show_chat

        Get a chat by id
        """
        pass

    def test_update_last_seen_message_id(self) -> None:
        """Test case for update_last_seen_message_id

        Update last seen message for the chat
        """
        pass


if __name__ == '__main__':
    unittest.main()
