# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.wellness import Wellness

class TestWellness(unittest.TestCase):
    """Wellness unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Wellness:
        """Test Wellness
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Wellness`
        """
        model = Wellness()
        if include_optional:
            return Wellness(
                id = '',
                ctl = 1.337,
                atl = 1.337,
                ramp_rate = 1.337,
                ctl_load = 1.337,
                atl_load = 1.337,
                sport_info = [
                    intervals_icu_client.models.sport_info.SportInfo(
                        type = 'Ride', 
                        eftp = 1.337, 
                        w_prime = 1.337, 
                        p_max = 1.337, )
                    ],
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                weight = 1.337,
                resting_hr = 56,
                hrv = 1.337,
                hrv_sdnn = 1.337,
                menstrual_phase = 'PERIOD',
                menstrual_phase_predicted = 'PERIOD',
                kcal_consumed = 56,
                sleep_secs = 56,
                sleep_score = 1.337,
                sleep_quality = 56,
                avg_sleeping_hr = 1.337,
                soreness = 56,
                fatigue = 56,
                stress = 56,
                mood = 56,
                motivation = 56,
                injury = 56,
                sp_o2 = 1.337,
                systolic = 56,
                diastolic = 56,
                hydration = 56,
                hydration_volume = 1.337,
                readiness = 1.337,
                baevsky_si = 1.337,
                blood_glucose = 1.337,
                lactate = 1.337,
                body_fat = 1.337,
                abdomen = 1.337,
                vo2max = 1.337,
                comments = '',
                steps = 56,
                respiration = 1.337,
                locked = True,
                temp_weight = True,
                temp_resting_hr = True
            )
        else:
            return Wellness(
        )
        """

    def testWellness(self):
        """Test Wellness"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
