# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.activity_hr_curve_payload import ActivityHRCurvePayload

class TestActivityHRCurvePayload(unittest.TestCase):
    """ActivityHRCurvePayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivityHRCurvePayload:
        """Test ActivityHRCurvePayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivityHRCurvePayload`
        """
        model = ActivityHRCurvePayload()
        if include_optional:
            return ActivityHRCurvePayload(
                secs = [
                    56
                    ],
                curves = [
                    intervals_icu_client.models.activity_hr_curve.ActivityHRCurve(
                        id = '', 
                        start_date_local = '', 
                        weight = 1.337, 
                        bpm = [
                            56
                            ], )
                    ]
            )
        else:
            return ActivityHRCurvePayload(
        )
        """

    def testActivityHRCurvePayload(self):
        """Test ActivityHRCurvePayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
