# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.duplicate_events_dto import DuplicateEventsDTO

class TestDuplicateEventsDTO(unittest.TestCase):
    """DuplicateEventsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DuplicateEventsDTO:
        """Test DuplicateEventsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DuplicateEventsDTO`
        """
        model = DuplicateEventsDTO()
        if include_optional:
            return DuplicateEventsDTO(
                num_copies = 56,
                weeks_between = 56,
                event_ids = [
                    56
                    ]
            )
        else:
            return DuplicateEventsDTO(
        )
        """

    def testDuplicateEventsDTO(self):
        """Test DuplicateEventsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
