# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.power_hr_curve import PowerHRCurve

class TestPowerHRCurve(unittest.TestCase):
    """PowerHRCurve unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PowerHRCurve:
        """Test PowerHRCurve
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PowerHRCurve`
        """
        model = PowerHRCurve()
        if include_optional:
            return PowerHRCurve(
                athlete_id = '',
                start = '',
                end = '',
                min_watts = 56,
                max_watts = 56,
                bucket_size = 56,
                bpm = [
                    56
                    ],
                cadence = [
                    56
                    ],
                minutes = [
                    56
                    ],
                lthr = 56,
                max_hr = 56,
                ftp = 56
            )
        else:
            return PowerHRCurve(
        )
        """

    def testPowerHRCurve(self):
        """Test PowerHRCurve"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
