# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.icu_segment import IcuSegment

class TestIcuSegment(unittest.TestCase):
    """IcuSegment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IcuSegment:
        """Test IcuSegment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IcuSegment`
        """
        model = IcuSegment()
        if include_optional:
            return IcuSegment(
                id = 56,
                start_index = 56,
                end_index = 56,
                name = '',
                segment_id = 56,
                starred = True
            )
        else:
            return IcuSegment(
        )
        """

    def testIcuSegment(self):
        """Test IcuSegment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
