# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.chat import Chat

class TestChat(unittest.TestCase):
    """Chat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Chat:
        """Test Chat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Chat`
        """
        model = Chat()
        if include_optional:
            return Chat(
                id = 56,
                type = 'PRIVATE',
                coaching_group = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                picture = '',
                description = '',
                url = '',
                slug = '',
                pub = True,
                join_policy = 'OPEN',
                sidebar_logo = '',
                sidebar_color = '',
                sidebar_dark = True,
                sidebar_top_color = '',
                hide_members = True,
                members_cannot_chat = True,
                primary_group = True,
                coins = 1.337,
                members = [
                    intervals_icu_client.models.chat_member.ChatMember(
                        athlete_id = '', 
                        name = '', 
                        profile_medium = '', 
                        role = 'MEMBER', 
                        coach = True, 
                        plan = 'FREE', 
                        accepted_coaching_group = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                athlete_id = '',
                activity_id = '',
                other_athlete_id = '',
                other_athlete_sex = '',
                follows_you = '',
                you_follow = '',
                role = 'MEMBER',
                new_message_count = 56,
                kicked = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                kicked_by_id = '',
                last_seen_message_id = 56,
                mute_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                shared_folders = [
                    intervals_icu_client.models.folder.Folder(
                        athlete_id = '', 
                        id = 56, 
                        type = 'FOLDER', 
                        name = '', 
                        description = '', 
                        children = [
                            intervals_icu_client.models.workout.Workout(
                                athlete_id = '', 
                                id = 56, 
                                icu_training_load = 56, 
                                name = '', 
                                description = '', 
                                type = '', 
                                indoor = True, 
                                color = '', 
                                moving_time = 56, 
                                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                joules = 56, 
                                joules_above_ftp = 56, 
                                workout_doc = {
                                    'key' : None
                                    }, 
                                folder_id = 56, 
                                day = 56, 
                                days = 56, 
                                plan_applied = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                hide_from_athlete = True, 
                                target = 'AUTO', 
                                targets = [
                                    'AUTO'
                                    ], 
                                carbs_per_hour = 56, 
                                tags = [
                                    ''
                                    ], 
                                attachments = [
                                    intervals_icu_client.models.attachment.Attachment(
                                        id = '', 
                                        filename = '', 
                                        mimetype = '', 
                                        url = '', )
                                    ], 
                                time = '', 
                                sub_type = 'NONE', 
                                for_week = True, 
                                distance = 1.337, 
                                icu_intensity = 1.337, )
                            ], 
                        visibility = 'PRIVATE', 
                        start_date_local = '', 
                        rollout_weeks = 56, 
                        auto_rollout_day = 56, 
                        read_only_workouts = True, 
                        starting_ctl = 56, 
                        starting_atl = 56, 
                        activity_types = [
                            'Ride'
                            ], 
                        num_workouts = 56, 
                        duration_weeks = 56, 
                        hours_per_week_min = 56, 
                        hours_per_week_max = 56, 
                        workout_targets = [
                            'AUTO'
                            ], 
                        blurb = '', 
                        can_edit = True, 
                        shared_with_count = 56, 
                        share_token = '', 
                        owner = intervals_icu_client.models.athlete_search_result.AthleteSearchResult(
                            id = '', 
                            name = '', 
                            profile_medium = '', 
                            city = '', 
                            state = '', 
                            country = '', 
                            timezone = '', 
                            sex = '', 
                            bio = '', 
                            website = '', 
                            email = '', ), )
                    ]
            )
        else:
            return Chat(
        )
        """

    def testChat(self):
        """Test Chat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
