# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.api.athletes_api import AthletesApi


class TestAthletesApi(unittest.TestCase):
    """AthletesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AthletesApi()

    def tearDown(self) -> None:
        pass

    def test_get_athlete(self) -> None:
        """Test case for get_athlete

        Get the athlete with sportSettings and custom_items
        """
        pass

    def test_get_athlete_profile(self) -> None:
        """Test case for get_athlete_profile

        Get athlete profile info
        """
        pass

    def test_get_athlete_summary(self) -> None:
        """Test case for get_athlete_summary

        Summary information for followed athletes
        """
        pass

    def test_get_athlete_training_plan(self) -> None:
        """Test case for get_athlete_training_plan

        Get the athlete's training plan
        """
        pass

    def test_get_settings(self) -> None:
        """Test case for get_settings

        Get the athlete's settings for phone, tablet or desktop
        """
        pass

    def test_update_athlete(self) -> None:
        """Test case for update_athlete

        Update an athlete
        """
        pass

    def test_update_athlete_plan(self) -> None:
        """Test case for update_athlete_plan

        Change the athlete's training plan
        """
        pass

    def test_update_athlete_plans(self) -> None:
        """Test case for update_athlete_plans

        Change training plans for a list of athletes
        """
        pass


if __name__ == '__main__':
    unittest.main()
