# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.event import Event

class TestEvent(unittest.TestCase):
    """Event unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Event:
        """Test Event
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Event`
        """
        model = Event()
        if include_optional:
            return Event(
                id = 56,
                start_date_local = '',
                icu_training_load = 56,
                icu_atl = 1.337,
                icu_ctl = 1.337,
                type = '',
                carbs_used = 56,
                ss_p_max = 1.337,
                ss_w_prime = 1.337,
                ss_cp = 1.337,
                calendar_id = 56,
                uid = '',
                athlete_id = '',
                category = 'WORKOUT',
                end_date_local = '',
                name = '',
                description = '',
                indoor = True,
                color = '',
                moving_time = 56,
                icu_ftp = 56,
                w_prime = 56,
                p_max = 56,
                atl_days = 56,
                ctl_days = 56,
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                not_on_fitness_chart = True,
                show_as_note = True,
                show_on_ctl_line = True,
                for_week = True,
                target = 'AUTO',
                joules = 56,
                joules_above_ftp = 56,
                workout_doc = {
                    'key' : None
                    },
                push_errors = [
                    intervals_icu_client.models.push_error.PushError(
                        service = '', 
                        message = '', 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                athlete_cannot_edit = True,
                hide_from_athlete = True,
                structure_read_only = True,
                created_by_id = '',
                shared_event_id = 56,
                entered = True,
                carbs_per_hour = 56,
                sub_type = 'NONE',
                distance = 1.337,
                tags = [
                    ''
                    ],
                attachments = [
                    intervals_icu_client.models.attachment.Attachment(
                        id = '', 
                        filename = '', 
                        mimetype = '', 
                        url = '', )
                    ],
                oauth_client_id = 56,
                external_id = '',
                load_target = 56,
                time_target = 56,
                distance_target = 1.337,
                plan_athlete_id = '',
                plan_folder_id = 56,
                plan_workout_id = 56,
                plan_applied = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                icu_intensity = 1.337,
                strain_score = 1.337
            )
        else:
            return Event(
        )
        """

    def testEvent(self):
        """Test Event"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
