# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.athlete_training_plan_update import AthleteTrainingPlanUpdate

class TestAthleteTrainingPlanUpdate(unittest.TestCase):
    """AthleteTrainingPlanUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AthleteTrainingPlanUpdate:
        """Test AthleteTrainingPlanUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AthleteTrainingPlanUpdate`
        """
        model = AthleteTrainingPlanUpdate()
        if include_optional:
            return AthleteTrainingPlanUpdate(
                id = '',
                training_plan_id = 56,
                training_plan_start_date = '',
                training_plan_alias = ''
            )
        else:
            return AthleteTrainingPlanUpdate(
        )
        """

    def testAthleteTrainingPlanUpdate(self):
        """Test AthleteTrainingPlanUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
