# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.time import Time

class TestTime(unittest.TestCase):
    """Time unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Time:
        """Test Time
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Time`
        """
        model = Time()
        if include_optional:
            return Time(
                start_secs = 56,
                end_secs = 56,
                index = 56,
                temp = 1.337,
                feels_like = 1.337,
                humidity = 56,
                wind_speed = 1.337,
                wind_deg = 56,
                wind_gust = 1.337,
                rain = 1.337,
                showers = 1.337,
                snow = 1.337,
                clouds = 56,
                pressure = 1.337,
                weather_code = 56
            )
        else:
            return Time(
        )
        """

    def testTime(self):
        """Test Time"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
