# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.hr_load_model import HRLoadModel

class TestHRLoadModel(unittest.TestCase):
    """HRLoadModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HRLoadModel:
        """Test HRLoadModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HRLoadModel`
        """
        model = HRLoadModel()
        if include_optional:
            return HRLoadModel(
                type = 'AVG_HR',
                icu_training_load = 56,
                training_data_count = 56
            )
        else:
            return HRLoadModel(
        )
        """

    def testHRLoadModel(self):
        """Test HRLoadModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
