# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.interval import Interval

class TestInterval(unittest.TestCase):
    """Interval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Interval:
        """Test Interval
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Interval`
        """
        model = Interval()
        if include_optional:
            return Interval(
                start_index = 56,
                distance = 1.337,
                moving_time = 56,
                elapsed_time = 56,
                average_watts = 56,
                average_watts_alt = 56,
                average_watts_alt_acc = 56,
                min_watts = 56,
                max_watts = 56,
                average_watts_kg = 1.337,
                max_watts_kg = 1.337,
                intensity = 56,
                w5s_variability = 1.337,
                weighted_average_watts = 56,
                training_load = 1.337,
                joules = 56,
                joules_above_ftp = 56,
                decoupling = 1.337,
                avg_lr_balance = 1.337,
                average_dfa_a1 = 1.337,
                average_epoc = 1.337,
                wbal_start = 56,
                wbal_end = 56,
                average_respiration = 1.337,
                average_tidal_volume = 1.337,
                average_tidal_volume_min = 1.337,
                zone = 56,
                zone_min_watts = 56,
                zone_max_watts = 56,
                average_speed = 1.337,
                min_speed = 1.337,
                max_speed = 1.337,
                gap = 1.337,
                average_heartrate = 56,
                min_heartrate = 56,
                max_heartrate = 56,
                average_cadence = 1.337,
                min_cadence = 56,
                max_cadence = 56,
                average_torque = 1.337,
                min_torque = 1.337,
                max_torque = 1.337,
                total_elevation_gain = 1.337,
                min_altitude = 1.337,
                max_altitude = 1.337,
                average_gradient = 1.337,
                average_smo2 = 1.337,
                average_thb = 1.337,
                average_smo2_2 = 1.337,
                average_thb_2 = 1.337,
                average_temp = 1.337,
                average_weather_temp = 1.337,
                average_feels_like = 1.337,
                average_wind_speed = 1.337,
                average_wind_gust = 1.337,
                prevailing_wind_deg = 56,
                average_yaw = 1.337,
                headwind_percent = 1.337,
                tailwind_percent = 1.337,
                strain_score = 1.337,
                ss_p_max = 1.337,
                ss_w_prime = 1.337,
                ss_cp = 1.337,
                id = 56,
                type = 'RECOVERY',
                end_index = 56,
                group_id = '',
                segment_effort_ids = [
                    56
                    ],
                start_time = 56,
                end_time = 56,
                label = '',
                average_stride = 1.337
            )
        else:
            return Interval(
        )
        """

    def testInterval(self):
        """Test Interval"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
