# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.models.pace_model import PaceModel

class TestPaceModel(unittest.TestCase):
    """PaceModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaceModel:
        """Test PaceModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaceModel`
        """
        model = PaceModel()
        if include_optional:
            return PaceModel(
                type = 'CS',
                critical_speed = 1.337,
                d_prime = 1.337,
                r2 = 1.337,
                input_point_indexes = [
                    56
                    ]
            )
        else:
            return PaceModel(
        )
        """

    def testPaceModel(self):
        """Test PaceModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
