# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.api.o_auth_server_controller_api import OAuthServerControllerApi


class TestOAuthServerControllerApi(unittest.TestCase):
    """OAuthServerControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthServerControllerApi()

    def tearDown(self) -> None:
        pass

    def test_disconnect_app(self) -> None:
        """Test case for disconnect_app

        Disconnect the athlete from the app matching the bearer token
        """
        pass


if __name__ == '__main__':
    unittest.main()
