# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intervals_icu_client.api.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsApi()

    def tearDown(self) -> None:
        pass

    def test_create_event(self) -> None:
        """Test case for create_event

        Create an event on the athlete's calendar
        """
        pass

    def test_create_multiple_events(self) -> None:
        """Test case for create_multiple_events

        Create multiple events on the athlete's calendar
        """
        pass

    def test_delete_event(self) -> None:
        """Test case for delete_event

        Delete an event from an athlete's calendar
        """
        pass

    def test_delete_events(self) -> None:
        """Test case for delete_events

        Delete a range of events from the athlete's calendar
        """
        pass

    def test_delete_events_bulk(self) -> None:
        """Test case for delete_events_bulk

        Delete events from an athlete's calendar by id or external_id
        """
        pass

    def test_download_workout1(self) -> None:
        """Test case for download_workout1

        Download a planned workout in zwo, mrc, erg or fit format
        """
        pass

    def test_download_workouts(self) -> None:
        """Test case for download_workouts

        Download one or more workouts from the athlete's calendar in a zip file
        """
        pass

    def test_duplicate_events(self) -> None:
        """Test case for duplicate_events

        Duplicate one or more events on the athlete's calendar
        """
        pass

    def test_list_events(self) -> None:
        """Test case for list_events

        List events (planned workouts, notes etc.) on the athlete's calendar, add .csv for CSV output
        """
        pass

    def test_list_fitness_model_events(self) -> None:
        """Test case for list_fitness_model_events

        List events that influence the athlete's fitness calculation in ascending date order
        """
        pass

    def test_list_tags1(self) -> None:
        """Test case for list_tags1

        List all tags that have been applied to events on the athlete's calendar
        """
        pass

    def test_mark_event_as_done(self) -> None:
        """Test case for mark_event_as_done

        Create a manual activity to match a planned workout
        """
        pass

    def test_show_event(self) -> None:
        """Test case for show_event

        Get an event
        """
        pass

    def test_update_event(self) -> None:
        """Test case for update_event

        Update an event
        """
        pass

    def test_update_events(self) -> None:
        """Test case for update_events

        Update all events for a date range at once. Only hide_from_athlete and athlete_cannot_edit can be updated
        """
        pass


if __name__ == '__main__':
    unittest.main()
