# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from intervals_icu_client.models.folder import Folder
from typing import Optional, Set
from typing_extensions import Self

class AthleteTrainingPlan(BaseModel):
    """
    AthleteTrainingPlan
    """ # noqa: E501
    athlete_id: Optional[StrictStr] = None
    training_plan_id: Optional[StrictInt] = None
    training_plan_start_date: Optional[StrictStr] = None
    timezone: Optional[StrictStr] = None
    training_plan_last_applied: Optional[datetime] = None
    training_plan: Optional[Folder] = None
    training_plan_alias: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["athlete_id", "training_plan_id", "training_plan_start_date", "timezone", "training_plan_last_applied", "training_plan", "training_plan_alias"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AthleteTrainingPlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of training_plan
        if self.training_plan:
            _dict['training_plan'] = self.training_plan.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AthleteTrainingPlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "athlete_id": obj.get("athlete_id"),
            "training_plan_id": obj.get("training_plan_id"),
            "training_plan_start_date": obj.get("training_plan_start_date"),
            "timezone": obj.get("timezone"),
            "training_plan_last_applied": obj.get("training_plan_last_applied"),
            "training_plan": Folder.from_dict(obj["training_plan"]) if obj.get("training_plan") is not None else None,
            "training_plan_alias": obj.get("training_plan_alias")
        })
        return _obj


