# coding: utf-8

"""
    Intervals.icu API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from intervals_icu_client.models.activity_filter import ActivityFilter
from intervals_icu_client.models.pace_model import PaceModel
from typing import Optional, Set
from typing_extensions import Self

class PaceCurve(BaseModel):
    """
    PaceCurve
    """ # noqa: E501
    id: Optional[StrictStr] = None
    filters: Optional[List[ActivityFilter]] = None
    label: Optional[StrictStr] = None
    filter_label: Optional[StrictStr] = None
    percentile: Optional[Union[StrictFloat, StrictInt]] = None
    start_date_local: Optional[StrictStr] = None
    end_date_local: Optional[StrictStr] = None
    days: Optional[StrictInt] = None
    moving_time: Optional[StrictInt] = None
    training_load: Optional[StrictInt] = None
    weight: Optional[Union[StrictFloat, StrictInt]] = None
    distance: Optional[List[Union[StrictFloat, StrictInt]]] = None
    values: Optional[List[StrictInt]] = None
    submax_values: Optional[List[List[StrictInt]]] = None
    submax_activity_id: Optional[List[List[StrictStr]]] = None
    start_index: Optional[List[StrictInt]] = None
    end_index: Optional[List[StrictInt]] = None
    activity_id: Optional[List[StrictStr]] = None
    type: Optional[StrictStr] = None
    pace_models: Optional[List[PaceModel]] = Field(default=None, alias="paceModels")
    __properties: ClassVar[List[str]] = ["id", "filters", "label", "filter_label", "percentile", "start_date_local", "end_date_local", "days", "moving_time", "training_load", "weight", "distance", "values", "submax_values", "submax_activity_id", "start_index", "end_index", "activity_id", "type", "paceModels"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['POWER', 'HR', 'PACE', 'GAP']):
            raise ValueError("must be one of enum values ('POWER', 'HR', 'PACE', 'GAP')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaceCurve from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pace_models (list)
        _items = []
        if self.pace_models:
            for _item_pace_models in self.pace_models:
                if _item_pace_models:
                    _items.append(_item_pace_models.to_dict())
            _dict['paceModels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaceCurve from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "filters": [ActivityFilter.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "label": obj.get("label"),
            "filter_label": obj.get("filter_label"),
            "percentile": obj.get("percentile"),
            "start_date_local": obj.get("start_date_local"),
            "end_date_local": obj.get("end_date_local"),
            "days": obj.get("days"),
            "moving_time": obj.get("moving_time"),
            "training_load": obj.get("training_load"),
            "weight": obj.get("weight"),
            "distance": obj.get("distance"),
            "values": obj.get("values"),
            "submax_values": obj.get("submax_values"),
            "submax_activity_id": obj.get("submax_activity_id"),
            "start_index": obj.get("start_index"),
            "end_index": obj.get("end_index"),
            "activity_id": obj.get("activity_id"),
            "type": obj.get("type"),
            "paceModels": [PaceModel.from_dict(_item) for _item in obj["paceModels"]] if obj.get("paceModels") is not None else None
        })
        return _obj


